# Docked complex PDB files
# Layout: {bucket}/{job_id}/assets/complex.pdb
#          {bucket}/{job_id}/assets/receptor.pdb
#          {bucket}/{job_id}/assets/ligand.sdf
#
# Access: presigned URLs generated by the API (7-day expiry).
# Bucket is fully private — no public ACLs, no bucket policy granting public read.

resource "aws_s3_bucket" "docked" {
  bucket = var.s3_bucket
  tags   = local.tags
}

# Block all public access — objects are served via presigned URLs only
resource "aws_s3_bucket_public_access_block" "docked" {
  bucket = aws_s3_bucket.docked.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# CORS so browsers can fetch presigned URLs directly (3Dmol viewer needs this)
resource "aws_s3_bucket_cors_configuration" "docked" {
  bucket = aws_s3_bucket.docked.id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["GET", "HEAD"]
    allowed_origins = ["*"]
    expose_headers  = ["ETag", "Content-Length"]
    max_age_seconds = 3600
  }
}

output "docked_bucket_name" {
  value = aws_s3_bucket.docked.bucket
}
